Hw1 thread
mascai/multithreading_cpp pull request #2
Opened 2020-10-04 21:50 UTC by mascai

2020-10-07 13:18 UTC, a-badin requested changes
Самая главная претензия: нужно запоминать состояние ваших дескрипторов, например, выставлять их в -1. Потому что у вас существует публичный метод close. Если после close вызвать read или write, вы можете испортить чужой файл. Более того деструктор Process тоже может закрыть не свой десткриптор и сломать поведение программы. Пример в котором через writeExact вы можете писать в случайный файл tmp
```
    PROCESS::Process proc("/bin/cat");
    proc.close();
    std::ofstream f1{"tmp"};
    std::ofstream f2{"tmp"};

    std::string buf{"Unexpected behaviour"};
    proc.writeExact(buf.c_str(), buf.size());
```

2020-10-07 13:18 UTC, a-badin commented on 01_safe_process/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
Нужно выставить ```set(CMAKE_CXX_STANDARD 17)``` перед add_executable тогда ```set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++1z")``` будет не нужен

2020-10-07 13:18 UTC, a-badin commented on 01_safe_process/main.cpp
> +#include "process.h"
обычно системные залоговки включают перед своими

2020-10-07 13:18 UTC, a-badin commented on 01_safe_process/main.cpp
> +        char* buf = new char[temp.size()];
Утечка памяти, не пользуемся new / delete , возьмите std::string и пишите в его буффер через data()

2020-10-07 13:18 UTC, a-badin commented on 01_safe_process/process.cpp
> +    pipe(p1);
нужно проверить, что нет ошибок

2020-10-07 13:18 UTC, a-badin commented on 01_safe_process/process.cpp
> +    int numBytes = ::write(fdWrite_, data, len);
write и read возвращают ssize_t 8 байт, их нельзя присваивать int 4 байта

2020-10-07 13:18 UTC, a-badin commented on 01_safe_process/process.cpp
> +    int curBytes = 0;
Еще раз размерность

2020-10-07 13:18 UTC, a-badin commented on 01_safe_process/process.cpp
> +        curBytes += write(curData, len - curBytes);
Если write вернет ошибку, счетчик начнет бесконечно убывать и будет бесконечный цикл

2020-10-07 13:18 UTC, a-badin commented on 01_safe_process/process.cpp
> +    pid_ = fork();
Пользоваться `::` для функций в глобальном пространстве имен - хорошая практика, давайте тогда пользоваться ей для всех вызовов

2020-10-07 13:18 UTC, a-badin commented on 01_safe_process/process.cpp
> +    ::close(fdWrite_);
нужно дождаться завершения дочернего процесса через вызов waitpid, а то не понятно зачем вы храните pid_.

2020-10-07 13:18 UTC, a-badin commented on 01_safe_process/process.h
> +    bool isReadable() const;
Реализации этого метода нет, нужно запоминать момент, когда read вернет 0, это признак того, что дочерний процесс закрыл свой stdout, а значит процесс больше не читаем

2020-10-07 13:18 UTC, a-badin commented on 01_safe_process/CMakeLists.txt
> +add_executable(process.bin  process.cpp process.h main.cpp)
Давайте раскидаем Process в билиотеку в отдельной папке lib, с src и include внутри. А main.cpp положим в src в корне

2020-10-08 16:08 UTC, a-badin commented on 01_safe_process/process.cpp
> +        curBytes += read(curData, len - curBytes);
если read вернет 0 будет бесконечный цикл

2020-10-08 19:16 UTC, mascai commented on 01_safe_process/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 17)
fixed

2020-10-08 19:22 UTC, mascai commented on 01_safe_process/main.cpp
> +        char* buf = new char[temp.size()];
fixed

2020-10-08 19:30 UTC, mascai commented on 01_safe_process/process.cpp
> +    int numBytes = ::write(fdWrite_, data, len);
fixed

2020-10-08 19:38 UTC, mascai commented on 01_safe_process/process.cpp
> +    int curBytes = 0;
fixed

2020-10-08 19:42 UTC, mascai commented on 01_safe_process/process.cpp
> +        curBytes += write(curData, len - curBytes);
Changed  type of ```numBytes```.
Overflow case eliminated.

```
size_t Process::write(const void* data, size_t len) {
    ssize_t numBytes = ::write(fdWrite_, data, len);
    if (numBytes < 0) {
        throw std::runtime_error("Invalid write()");
```

2020-10-08 19:45 UTC, mascai commented on 01_safe_process/process.cpp
> +    pid_ = fork();
I used ```::``` to resolve naming conlict (e.g. ::close and  PROCESS::close)

2020-10-08 19:46 UTC, mascai commented on 01_safe_process/process.cpp
> +        curBytes += read(curData, len - curBytes);
fixed

2020-10-08 21:47 UTC, mascai commented on 01_safe_process/CMakeLists.txt
> +add_executable(process.bin  process.cpp process.h main.cpp)
fixed

2020-10-08 22:35 UTC, mascai commented on 01_safe_process/process.cpp
> +    pipe(p1);
fixed

2020-10-09 18:39 UTC, a-badin requested changes

2020-10-09 18:39 UTC, a-badin commented on 01_safe_process/CMakeLists.txt
> +add_executable(process.bin  process_lib/include/process.h process_lib/src/process.cpp  main.cpp)
add_library(process process_lib/src/process.cpp)

add_executable(demo main.cpp)
target_link_libraries(demo process)

2020-10-09 18:39 UTC, a-badin commented on 01_safe_process/CMakeLists.txt
> +add_executable(process.bin  process_lib/include/process.h process_lib/src/process.cpp  main.cpp)
target_include_diretories(process PUBLIC process_lib/include)

2020-10-09 18:39 UTC, a-badin commented on 01_safe_process/main.cpp
> +#include "process_lib/include/process.h"
process.h

2020-10-09 18:39 UTC, a-badin commented on 01_safe_process/process_lib/src/process.cpp
> +        curBytes += read(curData, len - curBytes);
проверить что не ноль

2020-10-09 18:39 UTC, a-badin commented on 01_safe_process/process_lib/src/process.cpp
> +    fdRead_ = -1;
посылаем сигнал SIGINT,  и дождиаемся завершения

2020-10-12 19:21 UTC, mascai commented on 01_safe_process/process.cpp
> +    ::close(fdWrite_);
fixed

2020-10-12 19:49 UTC, mascai commented on 01_safe_process/process_lib/src/process.cpp
> +        curBytes += read(curData, len - curBytes);
fixed

2020-10-12 19:51 UTC, mascai commented on 01_safe_process/process_lib/src/process.cpp
> +    fdRead_ = -1;
fixed

2020-10-15 08:26 UTC, a-badin commented on 01_safe_process/process_lib/src/process.cpp
> +    fdWrite_ = -1;
Закрыть дескрипторы тоже нужно, сейчас в этой строчке утечка ресурсов.

2020-10-15 08:26 UTC, a-badin commented on 01_safe_process/main.cpp
> +#include "process_lib/include/process.h"
Так и осталось

2020-10-15 08:26 UTC, a-badin commented on 01_safe_process/CMakeLists.txt
> +add_executable(process.bin  process_lib/include/process.h process_lib/src/process.cpp  main.cpp)
Так и осталось

2020-10-18 10:51 UTC, a-badin commented on 01_safe_process/process_lib/src/process.cpp
> +    pid_t cpid = waitpid(pid_, &status, 0);
cpid все равно не используется, можно не объявлять

2020-10-18 10:51 UTC, a-badin commented on 01_safe_process/main.cpp
> +#include "process_lib/include/process.h"
Так и осталось

2020-10-18 10:51 UTC, a-badin commented on 01_safe_process/CMakeLists.txt
> +add_executable(process.bin  process_lib/include/process.h process_lib/src/process.cpp  main.cpp)
Так и осталось

2020-10-18 10:53 UTC, a-badin approved these changes
Добейте уже include в cmake и сливайте в мастер

2020-10-18 16:42 UTC, mascai commented
Added 
`include_directories(process_lib/include/)`

And simplified includes ("process_lib/include/process.h" --> "process.h")

2020-10-18 16:42 UTC, merged