HW_2: Initial commit. Added FileLogger
mascai/multithreading_cpp pull request #3
Opened 2020-10-16 17:36 UTC by mascai

2020-10-16 19:59 UTC, a-badin requested changes

2020-10-16 19:59 UTC, a-badin commented on 02_logger/log/src/FileLogger.cpp
> +#include "../include/FileLogger.h"
#include "FileLogger.h"

2020-10-16 19:59 UTC, a-badin commented on 02_logger/log/include/log.h
> +    ~BaseLogger() = default;
virtual

2020-10-16 19:59 UTC, a-badin commented on 02_logger/log/include/log.h
> +#include <string>
#pragma once

2020-10-18 17:48 UTC, mascai commented on 02_logger/log/src/FileLogger.cpp
> +#include "../include/FileLogger.h"
fixed

2020-10-18 17:51 UTC, mascai commented on 02_logger/log/include/log.h
> +    ~BaseLogger() = default;
fixed

2020-10-18 17:51 UTC, mascai commented on 02_logger/log/include/log.h
> +#include <string>
fixed

2020-10-20 15:56 UTC, a-badin requested changes

2020-10-20 15:56 UTC, a-badin commented on 02_logger/CMakeLists.txt
> +include_directories(log/include/)
target_include_directories

2020-10-20 15:56 UTC, a-badin commented on 02_logger/CMakeLists.txt
> +add_library(log_lib log/src/log.cpp log/src/FileLogger.cpp log/src/StdoutLogger.cpp log/src/StderrLogger.cpp)
сделайте отдельный cmake файл log/CMakeLists.txt, а здесь подключите его черещ add_subdirectory

2020-10-20 15:56 UTC, a-badin commented on 02_logger/log/include/FileLogger.h
> +    virtual ~FileLogger() {} // define destructor to eliminate "undefined reference to `vtable for LOG::BaseLogger'"
undefined reference to `vtable for LOG::BaseLogger' Это если вы что-то забыли скомпилировать, эту строчку можно убрать

2020-10-20 15:56 UTC, a-badin commented on 02_logger/log/include/StderrLogger.h
> +    virtual ~StderrLogger() {} // define destructor to eliminate "undefined reference to `vtable for LOG::BaseLogger'"
Должн работать без нее

2020-10-20 15:56 UTC, a-badin commented on 02_logger/log/include/StderrLogger.h
> +#include <fstream>
ненужен

2020-10-20 15:56 UTC, a-badin commented on 02_logger/log/include/StdoutLogger.h
> +#include <fstream>
ненужно

2020-11-02 12:26 UTC, merged